Please, no. Not my room...#speaker:Dannte #portrait:Dannte
This can't be happening. Not my boy. Please, wake up...
Elias, please... Please wake up...
Who could have done this? Why my son? I will find them. They will pay for this.